// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCartListApi;

#nullable disable

namespace ShoppingCartListApi.Migrations
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20230416192957_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ShoppingCartListApi.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<bool>("isPickedUp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("shoppingCart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemName = "Banana",
                            Quantity = 3.0,
                            isPickedUp = false
                        },
                        new
                        {
                            Id = 2,
                            ItemName = "Orange",
                            Quantity = 5.0,
                            isPickedUp = false
                        },
                        new
                        {
                            Id = 3,
                            ItemName = "Apple",
                            Quantity = 2.0,
                            isPickedUp = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
